import type { Metadata } from "next";
import { Noto_Sans } from "next/font/google";
import "./globals.css";

const NotoSans = Noto_Sans({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Testimonial Card",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${NotoSans.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
